backend:
  name: github
  repo: dngus64bp-commits/france-optical
  branch: main

media_folder: "images/common"
public_folder: "images/common"

locale: 'ko'

collections:
  - name: "site_data"
    label: "Contents"
    files:
      - name: "glasses"
        label: "Glasses Brands"
        file: "data/glasses.json"
        media_folder: "images/glasses"
        public_folder: "images/glasses"
        fields:
          - name: "brands"
            label: "Brands"
            label_singular: "Brand"
            widget: "list"
            summary: "{{fields.name}} ({{fields.name_kr}})"
            fields:
              - {name: "name", label: "Brand Name (EN)", widget: "string"}
              - {name: "name_kr", label: "Brand Name (KR)", widget: "string"}
              - {name: "image", label: "Brand Image", widget: "image", required: false}
              - {name: "description", label: "Description", widget: "text", required: false}
              - {name: "premium", label: "Premium", widget: "boolean", default: false}
              - name: "products"
                label: "Products"
                widget: "list"
                required: false
                summary: "{{fields.product_name}}"
                fields:
                  - {name: "product_name", label: "Product Name", widget: "string"}
                  - {name: "product_image", label: "Product Image", widget: "image", required: false}
                  - {name: "product_price", label: "Price", widget: "string", required: false}
                  - {name: "product_desc", label: "Product Description", widget: "string", required: false}

      - name: "lens"
        label: "Lens Brands"
        file: "data/lens.json"
        media_folder: "images/lens"
        public_folder: "images/lens"
        fields:
          - name: "brands"
            label: "Brands"
            label_singular: "Brand"
            widget: "list"
            summary: "{{fields.name}} ({{fields.name_kr}})"
            fields:
              - {name: "name", label: "Brand Name (EN)", widget: "string"}
              - {name: "name_kr", label: "Brand Name (KR)", widget: "string"}
              - {name: "image", label: "Brand Image", widget: "image", required: false}
              - {name: "description", label: "Description", widget: "text", required: false}
              - name: "products"
                label: "Products"
                widget: "list"
                required: false
                summary: "{{fields.product_name}}"
                fields:
                  - {name: "product_name", label: "Product Name", widget: "string"}
                  - {name: "product_image", label: "Product Image", widget: "image", required: false}
                  - {name: "product_price", label: "Price", widget: "string", required: false}
                  - {name: "product_desc", label: "Product Description", widget: "string", required: false}
